### ISSUE TITLE
Game Won't Launch (looks like it wants sponge) 1.12.2

### ISSUE THREAD

**Issue by KenyMylankca** [ldtteam/Performant#12]
**versions**
1.12.2-1.7
Forge:2847

[debug-3.log](https://github.com/ldtteam/Performant/files/4176935/debug-3.log)
[2020-02-09-3.log](https://github.com/ldtteam/Performant/files/4176936/2020-02-09-3.log)

**Comment by someaddons** [comment]
fixed in 1.8

**Comment by KenyMylankca** [comment]
doesn't work. it still crashes.
[latest.log](https://github.com/ldtteam/Performant/files/4365533/latest.log)
[debug.log](https://github.com/ldtteam/Performant/files/4365534/debug.log)

**Comment by someaddons** [comment]
Thats due to some incompatibility with other mods which are on the old 0.7 mixin like vanillafix
