### ISSUE TITLE
Lag-free Zombies causes Spawner issues

### ISSUE THREAD

**Issue by noobanidus** [ldtteam/Performant#22]
**Describe the bug**
I'm not 100% sure if this is an issue with Performant, but it appears to be the only thing modifying zombies in a fashion that could cause this.

With lag-free-zombies enabled (and disabled):

Spawners with zombies in them appear to be non-functional and revert to pigs. This happens with player-placed spawners primed with a zombie spawn egg, and with those naturally generated throughout the world.

In addition, Quark's "monster box" is spawning pigs which function similarly to zombies (and are detected with the zombie model by the One Probe).

**To Reproduce**
1. Place a spawner
2. Use a zombie spawn egg to prime the spawner
3. Pigs!

**Expected behavior**
Functional spawners.

**Screenshots**
Not applicable.

** Mod version **
Performant 1.15-1.11

** Logs **
None applicable. The only indication that Performant might be responsible was the registry replacement warning.

Unfortunately I can't provide much more information. 

EDIT: Removing Performant prevents this behaviour from happening.

**Comment by someaddons** [comment]
ye might be that it breaks spawners, I'll check. You can btw disable the zombies in the config

**Comment by someaddons** [comment]
spawners are fixed in v1.12, other mod's monster stuff may needs to wait a bit

**Comment by noobanidus** [comment]
This wasn't actually mine but a friends' server; they reckoned that they'd turned the option off and that it was still happening (i.e., the warning about registry replacement was still happening), but it's possible that they messed it up.

**Comment by someaddons** [comment]
might be that the warning still happens even when not replaced

**Comment by noobanidus** [comment]
Hm, that's triggered by the registration of something where the modid in the ResourceLocation doesn't match the modid of the current active mod container... so, it shouldn't happen. It's possible that they messed up the config, though.
